// M5Unified-ESP32P4 Version Information
#define M5UNIFIED_VERSION_MAJOR 0
#define M5UNIFIED_VERSION_MINOR 3
#define M5UNIFIED_VERSION_PATCH 0
#define M5UNIFIED_VERSION_ESP32P4 "-esp32p4"
#define M5UNIFIED_VERSION F( M5UNIFIED_VERSION_MAJOR "." M5UNIFIED_VERSION_MINOR "." M5UNIFIED_VERSION_PATCH M5UNIFIED_VERSION_ESP32P4 )
